name: CI

on:
  push:
    branches: [monitoring]
  pull_request:
    branches: [monitoring]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake g++ ninja-build linux-tools-common linux-tools-generic linux-tools-`uname -r`

    - name: Update Submodules
      run: |
        git submodule update --init --recursive

    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug

    - name: Build Project
      run: |
        cd build
        cmake --build .

    - name: Run Tests
      run: |
        cd build/tests
        ctest --output-on-failure
    
    - name: Monitoring Euclidean
      run: |
        cd build/bin
        perf stat -e cache-references,cache-misses ./monitoring brain 3 2 0 2> cache_stats.txt

    - name: Commit Cache Miss Data
      run: |
        git add cache_stats.txt
        git commit -m "Update cache miss stats" || echo "No changes"
        git push
