name: CI

on:
  push:
    branches: [monitoring]
  pull_request:
    branches: [monitoring]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake g++ ninja-build valgrind

    - name: Update Submodules
      run: |
        git submodule update --init --recursive

    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug

    - name: Build Project
      run: |
        cd build
        cmake --build .

    - name: Run Tests
      run: |
        cd build/tests
        ctest --output-on-failure


    - name: Valgrind Tests
      run: |
        cd build/bin
        valgrind --leak-check=full --show-leak-kinds=all --error-exitcode=1 ./monitoring test 3 2 1
